#!/usr/bin/env python3.6

# This file is part of Jenkins-Android-Emulator Helper.
#    Copyright (C) 2018  Michael Musenbrock
#
# Jenkins-Android-Helper is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Jenkins-Android-Helper is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Jenkins-Android-Helper.  If not, see <http://www.gnu.org/licenses/>.

## ANDROID_SDK_ROOT needs to be set to the Android SDK

import os
import sys
import subprocess

from jenkins_android_sdk import AndroidSDK
import ini_helper_functions
import android_emulator_helper_functions

_OPWD = os.getcwd()

### assume that the script runs locally
if not 'WORKSPACE' in os.environ:
    print("It seems that the script runs outside Jenkins. WORKSPACE will be set to PWD [" + _OPWD + "]!")
    os.environ["WORKSPACE"] = _OPWD

## Make sure the avd is installed in the current workspace
os.environ["ANDROID_AVD_HOME"] = os.environ["WORKSPACE"]

android_sdk = AndroidSDK()

IGNORE_RETURN_VALUE = False
RET_VAL = 0

def usage():
    print("""`basename $0` [ -I ] <command>

This is a simple wrapper for arbitrary command calls, with two specialities.
First the command will have the proper ANDROID_SERIAL set (most useful for gradle)
and secondly, if the call fails and the -I option is not given, it tries to execute
the kill command for the current running emulator.

OPTIONS:
  -I               Ignore the return value of the <command>, script will always return 0 and won't kill the emulator
  <command>        The command with parameters to execute. Having ANDROID_SERIAL set to the emulator started with this toolset
""")
    sys.exit(1)

def kill_emulator_on_failure():
    global RET_VAL

    if IGNORE_RETURN_VALUE:
        if RET_VAL != 0:
            print("Overwriting return code [%d] with 0" % (RET_VAL))
            RET_VAL = 0

    if RET_VAL != 0:
        android_emulator_kill_emulator()

    sys.exit(RET_VAL)

import atexit
atexit.register(kill_emulator_on_failure)

run_command = sys.argv[1:]

# If first parameter is '-I' ignore the return code of the executed command
if len(run_command) > 0 and run_command[0] == "-I":
    IGNORE_RETURN_VALUE = True
    run_command = run_command[1:]

# Print usage if no parameter is given
if run_command is None or len(run_command) == 0:
    usage
    sys.exit(0)

RET_VAL = android_sdk.run_command_with_android_serial_set(run_command, cwd=_OPWD)
kill_emulator_on_failure()
